load("//tooling/rules:repository_check.bzl", "repository_check")

filegroup(
    name = "files",
    srcs = glob(["BUCK", "*.sh"]),
    visibility = ["root//..."],
)

sh_binary(
    name = "repository-tools-command",
    main = "repository-tools.sh",
)

repository_check(
    name = "repository-tools-test",
    command = ":repository-tools-command",
    resources = ["//:scaffold"],
)

sh_binary(
    name = "tool-pins-command",
    main = "tool-pins.sh",
)

repository_check(
    name = "tool-pins-test",
    command = ":tool-pins-command",
    resources = ["//:scaffold"],
)
