go_library(
    name = "persistence",
    deps = [
        "//packages/reconcile:reconcile",
        "//packages/reconcile/datastore:datastore",
        "//packages/reconcile/datastore/dynamodb:dynamodb",
        "//packages/resources/content/s3:s3",
        "//packages/resources/datastore/dynamodb:dynamodb",
        "//services/intake/internal/intake:intake",
        "//vendor/github.com/aws/aws-sdk-go-v2/config:config",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/dynamodb:dynamodb",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/dynamodb/types:types",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/s3:s3",
    ],
    override_cgo_enabled = False,
    package_name = "github.com/p5/sir-robs-a-bot/services/intake/internal/persistence",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    tests = [":test"],
    visibility = ["//services/intake/..."],
)

go_test(
    name = "test",
    srcs = glob(["*_test.go"]),
    target_under_test = ":persistence",
)
